# Generated by Django 5.0.3 on 2024-03-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JustSending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bio', models.TextField(blank=True, null=True)),
                ('productImage', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('productSmallImage', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('isOnFrontPage', models.BooleanField(default=False)),
                ('createdAT', models.DateTimeField(auto_now_add=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'justSending',
                'ordering': ['createdAT'],
            },
        ),
    ]
