# Generated by Django 5.0.3 on 2024-03-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='justsending',
            name='productImage2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='justsending',
            name='productImage3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
