# Generated by Django 5.0.3 on 2024-03-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_justsending_productimage2_justsending_productimage3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ManyToManyField(related_name='coupon', to='core.justsending')),
            ],
            options={
                'verbose_name_plural': 'coupon',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('firstName', models.CharField(blank=True, max_length=255, null=True)),
                ('lastName', models.CharField(blank=True, max_length=255, null=True)),
                ('phoneNumber', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('fullName', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('pinCode', models.IntegerField()),
                ('phoneNumber2', models.IntegerField()),
                ('textNote', models.CharField(blank=True, max_length=955, null=True)),
                ('product', models.ManyToManyField(related_name='product', to='core.justsending')),
            ],
            options={
                'verbose_name_plural': 'orderItem',
            },
        ),
    ]
