# Generated by Django 5.0.3 on 2024-03-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_coupon_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstVariant', models.CharField(blank=True, max_length=255, null=True)),
                ('secondVariant', models.CharField(blank=True, max_length=255, null=True)),
                ('thirdVariant', models.CharField(blank=True, max_length=255, null=True)),
                ('fourthVariant', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'variation',
            },
        ),
    ]
