# Generated by Django 5.0.3 on 2024-03-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='product',
            field=models.ManyToManyField(related_name='variant', to='core.justsending'),
        ),
    ]
