# Generated by Django 5.0.3 on 2024-03-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_orderitem_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('secondModerTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('thirdModelTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('orThirdModeTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('productModelImage', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('secondsModerTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('thirdsModelTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('orsThirdModeTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('pTitleFirst', models.CharField(blank=True, max_length=255, null=True)),
                ('pTitleSecond', models.CharField(blank=True, max_length=255, null=True)),
                ('pThordTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('productModelSecondImage', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('createdAT', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'justSending',
                'ordering': ['createdAT'],
            },
        ),
    ]
