# Generated by Django 5.0.3 on 2024-03-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_modelproductmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelproductmodel',
            options={'ordering': ['createdAT'], 'verbose_name_plural': 'modelProductModel'},
        ),
        migrations.AddField(
            model_name='modelproductmodel',
            name='bgColor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='modelproductmodel',
            name='textColor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
