# Generated by Django 5.0.3 on 2024-03-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_justsending_bgcolor_justsending_firsttitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
